### ISSUE TITLE
clan.yml doesn't exits

### ISSUE THREAD

**Issue by MrCreeperMC** [Hysteria-Development/Practice#3]
Error occurred while enabling HyPractice v1.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'features/clans.yml' cannot be found in plugins/HyPractice.jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:252) ~[server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at com.hysteria.practice.utilities.file.type.BasicConfigurationFile.<init>(BasicConfigurationFile.java:24) ~[?:?]
        at com.hysteria.practice.utilities.file.type.BasicConfigurationFile.<init>(BasicConfigurationFile.java:34) ~[?:?]
        at com.hysteria.practice.HyPractice.loadConfig(HyPractice.java:292) ~[?:?]
        at com.hysteria.practice.HyPractice.onEnable(HyPractice.java:155) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:320) ~[server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:305) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:264) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:431) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:395) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:350) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:283) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:667) [server.jar:git-SportPaper-3931912-P.8d95b31-SP.f6b6479-CB.e1ebe52]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by CoderQCFromScraatch** [comment]
no it hasn't

**Comment by CoderQCFromScraatch** [comment]
![image](https://github.com/Devuxious/Practice/assets/73763394/a8fc724f-4ca4-4d2b-95b0-8350a63a1d4b)
where is it?
